[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = COM5
monitor_port = COM5
board_upload.before_reset = default_reset
board_upload.after_reset = hard_reset
lib_deps =
    electroniccats/MPU6050 @ ^1.3.0